# Generated by Django 3.0.3 on 2020-02-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=100)),
                ('Password', models.CharField(default='', max_length=100)),
                ('type1', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
