# Generated by Django 3.0.3 on 2020-02-24 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudumbasreeapp', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.CharField(default='', max_length=100)),
                ('current_date', models.CharField(default='', max_length=100)),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kudumbasreeapp.member')),
            ],
        ),
    ]
