# Generated by Django 3.0.3 on 2020-02-24 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudumbasreeapp', '0003_attendance_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaner', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('remarks', models.CharField(max_length=50)),
                ('borrower', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kudumbasreeapp.member')),
            ],
        ),
    ]
