# Generated by Django 3.0.3 on 2020-02-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudumbasreeapp', '0006_loan_repayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='balance',
            field=models.CharField(default='', max_length=100),
        ),
    ]
